### ISSUE TITLE
nodejs: call to undefined addEventListener causing problems

### ISSUE THREAD

**Issue by bwalex** [taoensso/sente#448]
https://github.com/taoensso/sente/blob/102c5b0b2ca8e1ce931655f146d770287f4a1b8b/src/taoensso/sente.cljc#L1353

This bit of code unconditionally calls the global addEventListener in all ClojureScript environments, including node.js. I use Sente as a server in a nodejs environment, all compiled with shadow-cljs - if that makes any difference. I'm currently on 1.16.2, and tried to update to 1.19.2, which is how I ran into it.

**Comment by ptaoussanis** [comment]
@bwalex Hi Alex- thanks for the report. PR welcome to exclude this behaviour from Node.js, otherwise I'll take care of this next time I'm on batched Sente work 👍
