### ISSUE TITLE
Questionable addEventListener "fix"

### ISSUE THREAD

**Issue by awkay** [taoensso/sente#458]
I was having the problem with addEventListener (electron/node) that this latest version fixes this way:

```
#?(:cljs
   (when-not node-target?
     (.addEventListener goog/global "beforeunload"
       (fn [event] (reset! client-unloading?_ true) nil))))
```

but I also use Sente in RN, and I'm pretty sure it will fail there too (unverified). Why not just wrap that in `catching` and forget about it? :D   Or at least flip the condition to browser targets?

**Comment by yoodame** [comment]
Confirmed that the latest version does fail in RN. Produces this error from the `taoensso.sente.js` file.

```
Uncaught Error
goog.global.addEventListener is not a function
```

```
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

**Comment by ptaoussanis** [comment]
> Why not just wrap that in catching and forget about it?

No good reason, just lack of familiarity with React Native :-) If just catching would be preferable, I'll make that change now 👍

**Comment by ptaoussanis** [comment]
@yoodame Thank you Yaw!

Do either of you maybe have a project you could recommend that's using both Sente and React Native? Would like to confirm that this is the only thing preventing RN support.

**Comment by yoodame** [comment]
I am currently working on an RN app with the latest Fulcro + Fulcro inspect tool. I've found 2 issues thus far. This one and another on encore - https://github.com/taoensso/encore/pull/81

**Comment by awkay** [comment]
Verified that this fixes the error for RN as well.

**Comment by awkay** [comment]
Thanks for the quick response!

**Comment by ptaoussanis** [comment]
Great news, and thanks for the quick confirmation! I'll cut Sente v1.20 final later today and include these fixes 👍

(Will keep this issue open till the release is out)

**Comment by ptaoussanis** [comment]
Preparing v1.20 release now, closing.
